'use client'
import {Nunito} from 'next/font/google'
import {usePathname} from 'next/navigation'
import {useEffect} from 'react'
import './globals.css'
import Script from "next/script";
import {ReactQueryProvider} from "@/Providers/ReactQuery.js";
// import getConfig from 'next/config';
//
// const {publicRuntimeConfig} = getConfig();


// export const metadata = {
// 	title: 'Next.js',
// 	description: 'Generated by Next.js',
// }
const montserrat = Nunito({subsets: ['latin']})

export default function RootLayout({children}) {
    const pathname = usePathname()
    useEffect(() => {
        // Check if the current route matches '/admin'
        if (pathname.startsWith('/admin')) {
            const overlayScrollbarsLink = document.createElement('link')
            overlayScrollbarsLink.rel = 'stylesheet'
            overlayScrollbarsLink.href =
                '/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'
            document.head.appendChild(overlayScrollbarsLink)

            const adminLteLink = document.createElement('link')
            adminLteLink.rel = 'stylesheet'
            adminLteLink.href =
                'https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css'
            document.head.appendChild(adminLteLink)

            // Cleanup function
            return () => {
                document.head.removeChild(overlayScrollbarsLink)
                document.head.removeChild(adminLteLink)
            }
        }
    }, [pathname])
    return (
        <html lang='en'>
        <body
            className={`${montserrat.className} ${pathname.startsWith('/admin') ? "sidebar-mini layout-fixed layout-navbar-fixed sidebar-collapse wrapper" : ''}`}
        >
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
        <Script src="https://kit.fontawesome.com/01bb16bf2a.js" crossOrigin="anonymous"/>
        <script
            src='https://code.jquery.com/jquery-3.6.0.min.js'
            integrity='sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4='
            crossOrigin='anonymous'
        ></script>

        <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
        </body>
        </html>
    )
}
